// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXx_u75U_sihRk6T2E2IrMxE_vjUhzTtw',
    appId: '1:239001759258:web:ce1365aa2e71f5e9e8eba3',
    messagingSenderId: '239001759258',
    projectId: 'bidayaapp-c770f',
    authDomain: 'bidayaapp-c770f.firebaseapp.com',
    storageBucket: 'bidayaapp-c770f.firebasestorage.app',
    measurementId: 'G-1NKWJ1CK6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ1aP32-w_wbv_Q-iSGJY2qEhH6i1LCCU',
    appId: '1:239001759258:android:10a2cd16dee07963e8eba3',
    messagingSenderId: '239001759258',
    projectId: 'bidayaapp-c770f',
    storageBucket: 'bidayaapp-c770f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAglRrrKjPBof3CmsBzipGOdqxC_nmOw24',
    appId: '1:239001759258:ios:6bf2dc115c7ed9e2e8eba3',
    messagingSenderId: '239001759258',
    projectId: 'bidayaapp-c770f',
    storageBucket: 'bidayaapp-c770f.firebasestorage.app',
    iosBundleId: 'com.zuniques.bidaya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAglRrrKjPBof3CmsBzipGOdqxC_nmOw24',
    appId: '1:239001759258:ios:6bf2dc115c7ed9e2e8eba3',
    messagingSenderId: '239001759258',
    projectId: 'bidayaapp-c770f',
    storageBucket: 'bidayaapp-c770f.firebasestorage.app',
    iosBundleId: 'com.zuniques.bidaya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXx_u75U_sihRk6T2E2IrMxE_vjUhzTtw',
    appId: '1:239001759258:web:9c67691968823588e8eba3',
    messagingSenderId: '239001759258',
    projectId: 'bidayaapp-c770f',
    authDomain: 'bidayaapp-c770f.firebaseapp.com',
    storageBucket: 'bidayaapp-c770f.firebasestorage.app',
    measurementId: 'G-494WSZ0R3W',
  );

}